app/oauth/forms.py
"""Implements forms used in the OAuth2 configuration ui."""

from flask_wtf import FlaskForm
from wtforms import (
    BooleanField,
    StringField, SubmitField, TextAreaField,
)
from wtforms.validators import Required


class ClientFormMixin():
    """Base form for question management forms."""
    name = StringField('Name', validators=[Required()])
    description = TextAreaField('Description')
    redirect = TextAreaField('Redirect URIs', validators=[Required()])
    scopes = TextAreaField('Default Scopes', validators=[Required()])
    confidential = BooleanField('Confidential?')


class NewClientForm(FlaskForm, ClientFormMixin):
    """Form to add a new question to the document database."""
    submit = SubmitField('Add client')


class EditClientForm(FlaskForm, ClientFormMixin):
    """Form to edit an existing question in the document database."""
    submit = SubmitField('Save changes')

app/oauth/__init__.py
"""Implements the OAuth2 authorization flow."""


__all__ = ['oauth']


from flask import Blueprint


oauth = Blueprint('oauth', __name__)


from . import (
    forms, views,
)


from datetime import (
    datetime, timedelta,
)

from flask_login import current_user

from app import oauth_provider as op, sql
from app.utils.models import (
    OAuth2Client, OAuth2Grant, OAuth2Token,
    User,
)


@op.clientgetter
def load_client(client_id):
    return OAuth2Client.query.filter_by(client_id=client_id).first()


@op.grantgetter
def load_grant(client_id, code):
    return OAuth2Grant.query.filter_by(client_id=client_id, code=code).first()


@op.grantsetter
def save_grant(client_id, code, request, *args, **kwargs):
    expires = datetime.utcnow() + timedelta(seconds=60)
    grant = OAuth2Grant(
        client_id=client_id,
        code=code['code'],
        redirect_uri=request.redirect_uri,
        _scopes=' '.join(request.scopes),
        user=current_user,
        expires=expires
    )
    sql.session.add(grant)
    sql.session.commit()
    return grant


@op.tokengetter
def load_token(access_token=None, refresh_token=None):
    if access_token:
        return OAuth2Token.query.filter_by(access_token=access_token).first()
    elif refresh_token:
        return OAuth2Token.query.filter_by(refresh_token=refresh_token).first()


@op.tokensetter
def save_token(token, request, *args, **kwargs):
    toks = OAuth2Token.query.filter_by(
        client_id=request.client.client_id, user_id=request.user.id)

    # Make sure that every client has only one token connected to a user
    for t in toks:
        sql.session.delete(t)

    expires_in = token.get('expires_in')
    expires = datetime.utcnow() + timedelta(seconds=expires_in)

    tok = OAuth2Token(
        access_token=token['access_token'],
        token_type=token['token_type'],
        _scopes=token['scope'],
        expires=expires,
        client_id=request.client.client_id,
        user_id=request.user.id
    )

    if request.body.get('grant_type') != 'client_credentials':
        tok.refresh_token = token['refresh_token']

    sql.session.add(tok)
    sql.session.commit()
    return tok


@op.usergetter
def get_user(username, password, *args, **kwargs):
    user = User.query.filter_by(username=username).first()
    if user.verify_password(password):
        return user
    return None

app/oauth/views.py
"""Implements OAuth2 authroization flow endpoints."""


from flask import (
    flash, redirect, render_template, request,
    url_for,
)
from flask_breadcrumbs import register_breadcrumb
from flask_login import (
    current_user, login_required,
)

from app import (
    oauth_provider as op, sql,
)
from app.confirm import confirm_required
from app.oauth import oauth
from app.oauth.forms import (
    NewClientForm, EditClientForm,
)
from app.utils.decorators import admin_required
from app.utils.models import OAuth2Client


@oauth.route('/authorize', methods=['GET', 'POST'])
@login_required
@op.authorize_handler
def authorize(*args, **kwargs):
    if request.method == 'GET':
        client_id = kwargs.get('client_id')
        client = OAuth2Client.query.filter_by(client_id=client_id).first()
        kwargs['client'] = client

        flash('Grant authorization to client "{0}"?'.format(
            client.name), 'warning')
        return render_template('oauth/authorize.html', **kwargs)

    confirm = request.form.get('confirm', 'no')
    return confirm == 'yes'


@oauth.route('/token', methods=['POST'])
@op.token_handler
def access_token():
    return None


@oauth.route('/revoke', methods=['POST'])
@op.revoke_handler
def revoke_token():
    pass


@oauth.route('/errors')
def error():
    page_vars = {
        'title': 'OAuth2 Error',
        'page_header': 'OAuth2 Error',
        'error': request.args['error'],
        'error_description': request.args['error_description']
    }
    return render_template('oauth/error.html', **page_vars)


@oauth.route('/clients')
@admin_required
@register_breadcrumb(oauth, 'bc.dash.oauthclients', 'OAuth2 Clients')
def clients():
    """Show list of authorized clients."""

    clients = OAuth2Client.query.all()

    page_vars = {
        'title': 'OAuth2 Clients',
        'navwell': True,
        'page_header': 'OAuth2 Clients',
        'clients': clients
    }
    return render_template('oauth/clients.html', **page_vars)


@oauth.route('/clients/new', methods=['GET', 'POST'])
@admin_required
@register_breadcrumb(oauth, 'bc.dash.oauthclients.new', 'New Client')
def new_client():
    """Render a form allowing the user to add an OAuth2 client."""

    form = NewClientForm()

    if form.validate_on_submit():
        client = OAuth2Client(
            name=form.name.data,
            description=form.description.data,
            user_id=current_user.id,
            client_id=OAuth2Client.generate_client_id(),
            client_secret=OAuth2Client.generate_client_secret(),
            is_confidential=form.confidential.data,
            _redirect_uris=form.redirect.data,
            _default_scopes=form.scopes.data
        )

        sql.session.add(client)
        sql.session.commit()

        flash('Client successfully added.', 'success')
        return redirect(url_for('oauth.client', cid=client.client_id))

    page_vars = {
        'title': 'New Client',
        'navwell': True,
        'page_header': 'New Client',
        'form': form
    }
    return render_template('oauth/new-client.html', **page_vars)


@oauth.route('/clients/<string:cid>/edit', methods=['GET', 'POST'])
@admin_required
@register_breadcrumb(oauth, 'bc.dash.oauthclients.edit', 'Edit Client')
def client(cid):
    """Render a form to edit an existing client."""
    client = OAuth2Client.query.filter_by(client_id=cid).first()
    form = EditClientForm()

    if form.validate_on_submit():
        client.name = form.name.data
        client.description = form.description.data
        client._redirect_uris = form.redirect.data
        client._default_scopes = form.scopes.data
        client.is_confidential = form.confidential.data

        sql.session.add(client)
        sql.session.commit()

        flash('Changes saved.', 'success')
        return redirect(url_for('oauth.client', cid=cid))

    form.name.data = client.name
    form.description.data = client.description
    form.redirect.data = client._redirect_uris
    form.scopes.data = client._default_scopes
    form.confidential.data = client.is_confidential

    page_vars = {
        'title': 'Edit Client',
        'navwell': True,
        'page_header': 'Edit Client',
        'form': form,
        'cid': cid
    }
    return render_template('oauth/edit-client.html', **page_vars)


@oauth.route('/clients/<string:cid>/delete')
@admin_required
@confirm_required(
    'Are you sure you want to delete this client?',
    'I am sure', 'oauth.client', ['cid'], 'danger'
)
def delete_client(cid):
    """Remove a client from the database."""
    client = OAuth2Client.query.filter_by(client_id=cid).first()
    sql.session.delete(client)
    sql.session.commit()

    flash('Client successfully deleted.', 'success')
    return redirect(url_for('oauth.clients'))


@oauth.route('/clients/<string:cid>/reset-secret')
@admin_required
@confirm_required(
    'Are you sure you want to reset the secret key for this client?',
    'I am sure', 'oauth.client', ['cid'], 'danger'
)
def reset_client_secret(cid):
    """Reset a client's secret key."""
    client = OAuth2Client.query.filter_by(client_id=cid).first()

    client.client_secret = OAuth2Client.generate_client_secret()

    sql.session.add(client)
    sql.session.commit()

    flash('Client secret successfully reset.', 'success')
    return redirect(url_for('oauth.client', cid=cid))


@oauth.route('/clients/<string:cid>/purge-grants')
@admin_required
@confirm_required(
    'Are you sure you want to purge grants for this client?',
    'I am sure', 'oauth.client', ['cid'], 'danger'
)
def purge_client_grants(cid):
    """Purge grants for a given client."""
    client = OAuth2Client.query.filter_by(client_id=cid).first()

    print(client.grants)

    for grant in client.grants:
        grant.delete()

    flash('Grants successfully purged.', 'success')
    return redirect(url_for('oauth.client', cid=cid))


@oauth.route('/clients/<string:cid>/purge-tokens')
@admin_required
@confirm_required(
    'Are you sure you want to purge tokens for this client?',
    'I am sure', 'oauth.client', ['cid'], 'danger'
)
def purge_client_tokens(cid):
    """Purge tokens for a given client."""
    client = OAuth2Client.query.filter_by(client_id=cid).first()

    for token in client.tokens:
        token.delete()

    flash('Tokens successfully purged.', 'success')
    return redirect(url_for('oauth.client', cid=cid))

app/templates/oauth/authorize.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}
<form method="post" class="form" role="form">
    <button class="btn btn-default" name="confirm" value="yes">Confirm</button>
    <button class="btn btn-default" name="confirm" value="no">Cancel</button>
</form>
{% endblock page_content %}

app/templates/oauth/clients.html
{% extends "base.html" %}

{% block page_actions %}
{{ super() }}
<a href="{{ url_for('oauth.new_client') }}" class="btn btn-default">New Client</a>
{% endblock page_actions %}

{% block page_content %}
{{ super() }}
<table class="table table-hover">
    <caption>{{ clients|length }} client{{ '' if clients|length == 1 else 's' }} registered.</caption>
    <thead>
        <tr>
            <th>Client</th>
            <th>Redirect URIs</th>
            <th>Identity</th>
        </tr>
    </thead>
    <tbody>
        {% for c in clients: %}
        <tr>
            <td class="col-md-3">
                <a href="{{ url_for('oauth.client', cid=c.client_id) }}">
                    {{ c.name }} ({{ 'Confidential' if c.is_confidential else 'Public' }})
                </a> <br />
                {{ c.description }} <br />
                Scopes: {{ c.default_scopes|join(', ') }}
            </td>
            <td class="col-md-3">
                {{ c.redirect_uris|join(', ') }}
            </td>
            <td class="col-md-6">
                ID: {{ c.client_id }}<br />
                Secret: {{ c.client_secret }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock page_content %}

app/templates/oauth/edit-client.html
{% extends "base.html" %}


{% block page_actions %}
{{ super() }}
<a href="{{ url_for('oauth.purge_client_grants', cid=cid) }}" class="btn btn-danger">Purge Grants</a>
<a href="{{ url_for('oauth.purge_client_tokens', cid=cid) }}" class="btn btn-danger">Purge Tokens</a>
<a href="{{ url_for('oauth.reset_client_secret', cid=cid) }}" class="btn btn-danger">Reset Secret</a>
<a href="{{ url_for('oauth.delete_client', cid=cid) }}" class="btn btn-danger">Delete</a>
{% endblock page_actions %}


{% block page_content %}
{{ super() }}
<div class="col-md-6">
    <form method="post" class="form" role="form">
        {{ form.hidden_tag() }}
        <div class="form-group
                        {% if form.name.errors %} has-error{% endif %}
                        {% if form.name.flags.required %} required{% endif %}">
            {{ form.name.label(class_='control-label') }}
            {{ form.name(class_='form-control') }}
            {% for message in form.name.errors %}
            <p class="help-block">{{ message }}</p>
            {% endfor %}
        </div>
        <div class="form-group
                        {% if form.description.errors %} has-error{% endif %}
                        {% if form.description.flags.required %} required{% endif %}">
            {{ form.description.label(class_='control-label') }}
            {{ form.description(class_='form-control', rows=5) }}
            {% for message in form.description.errors %}
            <p class="help-block">{{ message }}</p>
            {% endfor %}
        </div>
        <div class="form-group
                        {% if form.redirect.errors %} has-error{% endif %}
                        {% if form.redirect.flags.required %} required{% endif %}">
            {{ form.redirect.label(class_='control-label') }}
            {{ form.redirect(class_='form-control', rows=5) }}
            {% for message in form.redirect.errors %}
            <p class="help-block">{{ message }}</p>
            {% endfor %}
        </div>
        <div class="form-group
                        {% if form.scopes.errors %} has-error{% endif %}
                        {% if form.scopes.flags.required %} required{% endif %}">
            {{ form.scopes.label(class_='control-label') }}
            {{ form.scopes(class_='form-control', rows=5) }}
            {% for message in form.scopes.errors %}
            <p class="help-block">{{ message }}</p>
            {% endfor %}
        </div>
        <div class="checkbox">
            <label>
                {{ form.confidential }}
                {{ form.confidential.label.text }}
            </label>
        </div>
        
        <a role="button" class="btn btn-default"
                href="{{ url_for('oauth.client', cid=cid)}}">
                Cancel
        </a>
        {{ form.submit(class_='btn btn-default') }}
    </form>
</div>
{% endblock page_content %}

app/templates/oauth/error.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}
<p>{{ error }}</p>
<p>{{ error_description }}</p>
{% endblock page_content %}

app/templates/oauth/new-client.html
{% extends "base.html" %}


{% block page_content %}
{{ super() }}
<div class="col-md-6">
    <form method="post" class="form" role="form">
        {{ form.hidden_tag() }}
        <div class="form-group
                        {% if form.name.errors %} has-error{% endif %}
                        {% if form.name.flags.required %} required{% endif %}">
            {{ form.name.label(class_='control-label') }}
            {{ form.name(class_='form-control') }}
            {% for message in form.name.errors %}
            <p class="help-block">{{ message }}</p>
            {% endfor %}
        </div>
        <div class="form-group
                        {% if form.description.errors %} has-error{% endif %}
                        {% if form.description.flags.required %} required{% endif %}">
            {{ form.description.label(class_='control-label') }}
            {{ form.description(class_='form-control', rows=5) }}
            {% for message in form.description.errors %}
            <p class="help-block">{{ message }}</p>
            {% endfor %}
        </div>
        <div class="form-group
                        {% if form.redirect.errors %} has-error{% endif %}
                        {% if form.redirect.flags.required %} required{% endif %}">
            {{ form.redirect.label(class_='control-label') }}
            {{ form.redirect(class_='form-control', rows=5) }}
            {% for message in form.redirect.errors %}
            <p class="help-block">{{ message }}</p>
            {% endfor %}
        </div>
        <div class="form-group
                        {% if form.scopes.errors %} has-error{% endif %}
                        {% if form.scopes.flags.required %} required{% endif %}">
            {{ form.scopes.label(class_='control-label') }}
            {{ form.scopes(class_='form-control', rows=5) }}
            {% for message in form.scopes.errors %}
            <p class="help-block">{{ message }}</p>
            {% endfor %}
        </div>
        <div class="checkbox">
            <label>
                {{ form.confidential(checked=True) }}
                {{ form.confidential.label.text }}
            </label>
        </div>
        
        <a role="button" class="btn btn-default"
                href="{{ url_for('oauth.clients')}}">
                Cancel
        </a>
        {{ form.submit(class_='btn btn-default') }}
    </form>
</div>
{% endblock page_content %}